package com.example.demo.protoModel;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OCRAny.proto

public final class OCRAnyProtoModel {
  private OCRAnyProtoModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OCRAnyProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OCRAnyProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 ID = 1;</code>
     */
    int getID();

    /**
     * <pre>
     * 任意一种消息, 可根据 type_url 确定消息类型
     * </pre>
     *
     * <code>.google.protobuf.Any any = 2;</code>
     */
    boolean hasAny();
    /**
     * <pre>
     * 任意一种消息, 可根据 type_url 确定消息类型
     * </pre>
     *
     * <code>.google.protobuf.Any any = 2;</code>
     */
    com.google.protobuf.Any getAny();
    /**
     * <pre>
     * 任意一种消息, 可根据 type_url 确定消息类型
     * </pre>
     *
     * <code>.google.protobuf.Any any = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getAnyOrBuilder();
  }
  /**
   * Protobuf type {@code OCRAnyProto}
   */
  public  static final class OCRAnyProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OCRAnyProto)
      OCRAnyProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OCRAnyProto.newBuilder() to construct.
    private OCRAnyProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OCRAnyProto() {
      iD_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OCRAnyProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              iD_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (any_ != null) {
                subBuilder = any_.toBuilder();
              }
              any_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(any_);
                any_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OCRAnyProtoModel.internal_static_OCRAnyProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OCRAnyProtoModel.internal_static_OCRAnyProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OCRAnyProtoModel.OCRAnyProto.class, OCRAnyProtoModel.OCRAnyProto.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int iD_;
    /**
     * <code>int32 ID = 1;</code>
     */
    public int getID() {
      return iD_;
    }

    public static final int ANY_FIELD_NUMBER = 2;
    private com.google.protobuf.Any any_;
    /**
     * <pre>
     * 任意一种消息, 可根据 type_url 确定消息类型
     * </pre>
     *
     * <code>.google.protobuf.Any any = 2;</code>
     */
    public boolean hasAny() {
      return any_ != null;
    }
    /**
     * <pre>
     * 任意一种消息, 可根据 type_url 确定消息类型
     * </pre>
     *
     * <code>.google.protobuf.Any any = 2;</code>
     */
    public com.google.protobuf.Any getAny() {
      return any_ == null ? com.google.protobuf.Any.getDefaultInstance() : any_;
    }
    /**
     * <pre>
     * 任意一种消息, 可根据 type_url 确定消息类型
     * </pre>
     *
     * <code>.google.protobuf.Any any = 2;</code>
     */
    public com.google.protobuf.AnyOrBuilder getAnyOrBuilder() {
      return getAny();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (iD_ != 0) {
        output.writeInt32(1, iD_);
      }
      if (any_ != null) {
        output.writeMessage(2, getAny());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (iD_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, iD_);
      }
      if (any_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getAny());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OCRAnyProtoModel.OCRAnyProto)) {
        return super.equals(obj);
      }
      OCRAnyProtoModel.OCRAnyProto other = (OCRAnyProtoModel.OCRAnyProto) obj;

      boolean result = true;
      result = result && (getID()
          == other.getID());
      result = result && (hasAny() == other.hasAny());
      if (hasAny()) {
        result = result && getAny()
            .equals(other.getAny());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getID();
      if (hasAny()) {
        hash = (37 * hash) + ANY_FIELD_NUMBER;
        hash = (53 * hash) + getAny().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OCRAnyProtoModel.OCRAnyProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OCRAnyProtoModel.OCRAnyProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OCRAnyProtoModel.OCRAnyProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OCRAnyProtoModel.OCRAnyProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OCRAnyProtoModel.OCRAnyProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OCRAnyProtoModel.OCRAnyProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OCRAnyProtoModel.OCRAnyProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OCRAnyProtoModel.OCRAnyProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OCRAnyProtoModel.OCRAnyProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OCRAnyProtoModel.OCRAnyProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OCRAnyProtoModel.OCRAnyProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OCRAnyProtoModel.OCRAnyProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OCRAnyProtoModel.OCRAnyProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OCRAnyProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OCRAnyProto)
        OCRAnyProtoModel.OCRAnyProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OCRAnyProtoModel.internal_static_OCRAnyProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OCRAnyProtoModel.internal_static_OCRAnyProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OCRAnyProtoModel.OCRAnyProto.class, OCRAnyProtoModel.OCRAnyProto.Builder.class);
      }

      // Construct using OCRAnyProtoModel.OCRAnyProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        iD_ = 0;

        if (anyBuilder_ == null) {
          any_ = null;
        } else {
          any_ = null;
          anyBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OCRAnyProtoModel.internal_static_OCRAnyProto_descriptor;
      }

      public OCRAnyProtoModel.OCRAnyProto getDefaultInstanceForType() {
        return OCRAnyProtoModel.OCRAnyProto.getDefaultInstance();
      }

      public OCRAnyProtoModel.OCRAnyProto build() {
        OCRAnyProtoModel.OCRAnyProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public OCRAnyProtoModel.OCRAnyProto buildPartial() {
        OCRAnyProtoModel.OCRAnyProto result = new OCRAnyProtoModel.OCRAnyProto(this);
        result.iD_ = iD_;
        if (anyBuilder_ == null) {
          result.any_ = any_;
        } else {
          result.any_ = anyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OCRAnyProtoModel.OCRAnyProto) {
          return mergeFrom((OCRAnyProtoModel.OCRAnyProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OCRAnyProtoModel.OCRAnyProto other) {
        if (other == OCRAnyProtoModel.OCRAnyProto.getDefaultInstance()) return this;
        if (other.getID() != 0) {
          setID(other.getID());
        }
        if (other.hasAny()) {
          mergeAny(other.getAny());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OCRAnyProtoModel.OCRAnyProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OCRAnyProtoModel.OCRAnyProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int iD_ ;
      /**
       * <code>int32 ID = 1;</code>
       */
      public int getID() {
        return iD_;
      }
      /**
       * <code>int32 ID = 1;</code>
       */
      public Builder setID(int value) {
        
        iD_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ID = 1;</code>
       */
      public Builder clearID() {
        
        iD_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any any_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> anyBuilder_;
      /**
       * <pre>
       * 任意一种消息, 可根据 type_url 确定消息类型
       * </pre>
       *
       * <code>.google.protobuf.Any any = 2;</code>
       */
      public boolean hasAny() {
        return anyBuilder_ != null || any_ != null;
      }
      /**
       * <pre>
       * 任意一种消息, 可根据 type_url 确定消息类型
       * </pre>
       *
       * <code>.google.protobuf.Any any = 2;</code>
       */
      public com.google.protobuf.Any getAny() {
        if (anyBuilder_ == null) {
          return any_ == null ? com.google.protobuf.Any.getDefaultInstance() : any_;
        } else {
          return anyBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 任意一种消息, 可根据 type_url 确定消息类型
       * </pre>
       *
       * <code>.google.protobuf.Any any = 2;</code>
       */
      public Builder setAny(com.google.protobuf.Any value) {
        if (anyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          any_ = value;
          onChanged();
        } else {
          anyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 任意一种消息, 可根据 type_url 确定消息类型
       * </pre>
       *
       * <code>.google.protobuf.Any any = 2;</code>
       */
      public Builder setAny(
          com.google.protobuf.Any.Builder builderForValue) {
        if (anyBuilder_ == null) {
          any_ = builderForValue.build();
          onChanged();
        } else {
          anyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 任意一种消息, 可根据 type_url 确定消息类型
       * </pre>
       *
       * <code>.google.protobuf.Any any = 2;</code>
       */
      public Builder mergeAny(com.google.protobuf.Any value) {
        if (anyBuilder_ == null) {
          if (any_ != null) {
            any_ =
              com.google.protobuf.Any.newBuilder(any_).mergeFrom(value).buildPartial();
          } else {
            any_ = value;
          }
          onChanged();
        } else {
          anyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 任意一种消息, 可根据 type_url 确定消息类型
       * </pre>
       *
       * <code>.google.protobuf.Any any = 2;</code>
       */
      public Builder clearAny() {
        if (anyBuilder_ == null) {
          any_ = null;
          onChanged();
        } else {
          any_ = null;
          anyBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 任意一种消息, 可根据 type_url 确定消息类型
       * </pre>
       *
       * <code>.google.protobuf.Any any = 2;</code>
       */
      public com.google.protobuf.Any.Builder getAnyBuilder() {
        
        onChanged();
        return getAnyFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 任意一种消息, 可根据 type_url 确定消息类型
       * </pre>
       *
       * <code>.google.protobuf.Any any = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getAnyOrBuilder() {
        if (anyBuilder_ != null) {
          return anyBuilder_.getMessageOrBuilder();
        } else {
          return any_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : any_;
        }
      }
      /**
       * <pre>
       * 任意一种消息, 可根据 type_url 确定消息类型
       * </pre>
       *
       * <code>.google.protobuf.Any any = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getAnyFieldBuilder() {
        if (anyBuilder_ == null) {
          anyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getAny(),
                  getParentForChildren(),
                  isClean());
          any_ = null;
        }
        return anyBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OCRAnyProto)
    }

    // @@protoc_insertion_point(class_scope:OCRAnyProto)
    private static final OCRAnyProtoModel.OCRAnyProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OCRAnyProtoModel.OCRAnyProto();
    }

    public static OCRAnyProtoModel.OCRAnyProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OCRAnyProto>
        PARSER = new com.google.protobuf.AbstractParser<OCRAnyProto>() {
      public OCRAnyProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OCRAnyProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OCRAnyProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OCRAnyProto> getParserForType() {
      return PARSER;
    }

    public OCRAnyProtoModel.OCRAnyProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OCRAnyProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OCRAnyProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014OCRAny.proto\032\031google/protobuf/any.prot" +
      "o\"<\n\013OCRAnyProto\022\n\n\002ID\030\001 \001(\005\022!\n\003any\030\002 \001(" +
      "\0132\024.google.protobuf.AnyB\022B\020OCRAnyProtoMo" +
      "delb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_OCRAnyProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OCRAnyProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OCRAnyProto_descriptor,
        new java.lang.String[] { "ID", "Any", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
